### PR TITLE
Add install script for Windows

### PR DESCRIPTION
**Pull request by MoonMoonDogo**
Just a tiny pull request to add an equivalent to ``install.sh`` for Windows.

### CODE REVIEW

**Comment by GreatGodApollo** [comment]
Sorry, but I'm not too sure if this would work if users were using older versions of Ruby, didn't always include buildtools for windows, in that if you could find a way to check for that as that would be amazing, for now it will not be merged.

**Comment by MoonMoonDogo** [comment]
I can add version checking, that should not be a problem. What would be the minimum version?

**Comment by GreatGodApollo** [comment]
The first version of the Windows Installer for Ruby that comes with the dev tools is 2.4.0.
The minimum version of MinGW would be 4.7.2 I believe (just taking the latest number from the Win installer downloads page)
Thanks!

**Comment by MoonMoonDogo** [comment]
I've added a version check for ruby, PTAL.

**Comment by GreatGodApollo** [comment]
I believe you misunderstood me, users under 2.4.0 can still use the bot, it really doesn't matter the ruby version, in fact, I still run 2.3. It's just that the user needs MinGW (Windows Dev Tools).

**Comment by MoonMoonDogo** [comment]
I don't know how to check the version of MinGW in a reliable way. I think having an ``install.bat``, even without the check, is better than having nothing at all.

**Comment by GreatGodApollo** [comment]
I beg to differ, if there is an install.bat it needs to be as easy to use as possible. If there are things that users need to check themselves, that adds more confusion, and until this is implemented, this will not be merged.

**Pull request closed without merging**
